id: AA3272E9D
base_file: fAF00.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:19:18.849047
  last_modified_at: 2022-06-17 11:19:18.849050
