id: AA3272E9D
base_file: fC1B6.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:19:18.850342
  last_modified_at: 2022-06-17 11:19:18.850345
