id: AA3272E9D
base_file: f4E9C.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:19:18.830892
  last_modified_at: 2022-06-17 11:19:18.830904
